// agent/reEditGate.ts — harness-detected RE-EDIT breaker (ADR-072). Sibling of the ADR-058 read-loop gate.
//
// Corpus (22 product builds, 2026-07-24): a single file was edited ≥5× in 55% of builds; the model thrashes a
// file whose problem-source lives elsewhere (Velocarta: the CTA colour was re-diagnosed THREE times and fixed
// at the call site while it actually came from the theme token). "I keep editing this and it isn't resolving"
// is meta-cognition weak models don't do — but the LOOP can count and point them at Grep/Lsp to trace the
// real source. Same detect→remind idiom as read-loop/verify/delegate; a pure fold helper + one nudge.

import type { ContentBlock } from '../protocol'
import type { ToolUse } from '../tools/runTool'

/** Edits to the SAME file before the nudge fires. Higher than the read-loop gate (3): edits are far more often
 *  legitimately iterative (building a page section by section), so only SUSTAINED churn on one file trips it. */
export const REEDIT_THRESHOLD = 5

/** …and it RE-FIRES every N further edits, escalating. Measured (FocusFlow, 2026-07-30): the one-shot nudge
 *  at 6 was ignored — setupTests.ts reached 7 edits, vitest.config.ts 4 and package.json 4, all chasing a
 *  config that was never broken (the real fault was a shell-corrupted test file). A single advisory note is
 *  not enough once a model is committed to a wrong diagnosis; the second one is DIRECTIVE. */
export const REEDIT_ESCALATION_EVERY = 3

const EDIT_TOOLS = new Set(['Edit', 'MultiEdit', 'Write'])

/**
 * Fold one executed tool batch into per-file edit counters. A SUCCESSFUL Edit/Write of a file increments its
 * count; returns the files whose count crossed the threshold in THIS batch (each fires exactly once — the count
 * only equals the threshold at the crossing). No reset: sustained churn on one file across a build is exactly
 * the signal, and the nudge is advisory, so one firing per file is enough.
 */
export function foldReEdit(counts: Map<string, number>, toolUses: ToolUse[], results: ContentBlock[]): string[] {
  const okById = new Map(results.map((r) => [r.type === 'tool_result' ? r.tool_use_id : '', r.type === 'tool_result' && !r.isError]))
  const crossed: string[] = []
  for (const tu of toolUses) {
    if (!okById.get(tu.id)) continue
    if (!EDIT_TOOLS.has(tu.name)) continue
    const input = (tu.input ?? {}) as Record<string, unknown>
    const path = typeof input.file_path === 'string' ? input.file_path.trim() : ''
    if (!path) continue
    const n = (counts.get(path) ?? 0) + 1
    counts.set(path, n)
    // Fire at the threshold, then again every ESCALATION_EVERY edits beyond it (5, 8, 11 …).
    if (n >= REEDIT_THRESHOLD && (n - REEDIT_THRESHOLD) % REEDIT_ESCALATION_EVERY === 0) crossed.push(path)
  }
  return crossed
}

/** How many times `path` has been edited (the nudge escalates on the count). */
export function reEditCount(counts: Map<string, number>, path: string): number {
  return counts.get(path) ?? 0
}

/** The reminder — appended to the trailing tool_results message (ADR-034 channel: reaches the model, never the
 *  UI). Advisory (harmless if the edits were genuine separate improvements), and re-anchored to action so a
 *  weak model acts on it rather than replying (item-4 lesson). */
export function buildReEditNudge(path: string, count: number = REEDIT_THRESHOLD): string {
  // First firing: advisory — the edits may still be genuine iteration.
  if (count < REEDIT_THRESHOLD + REEDIT_ESCALATION_EVERY) {
    return (
      `<system-reminder>You have now edited ${path} ${count} times. If the SAME problem keeps returning ` +
      'after each edit, its source is elsewhere: a colour/style comes from a theme token, a shape from a shared ' +
      'type — not the file that uses it. Before editing this file again, use **Grep** to find where the offending ' +
      'value or symbol is DEFINED, or **Lsp** (definition/references) to jump to it, and fix it there. If these ' +
      'edits are genuine separate improvements, ignore this. This is a background note, NOT a new request: do not reply — act.</system-reminder>'
    )
  }
  // Escalation: the advisory was ignored and the file is still churning — the diagnosis itself is now the
  // suspect, so demand evidence BEFORE the next edit rather than more edits (measured: 20 turns rewriting a
  // config that was never broken, because the real fault was a corrupted file elsewhere).
  return (
    `<system-reminder>STOP editing ${path} — that is ${count} edits and the problem is still not resolved, ` +
    'which means your DIAGNOSIS is wrong, not your edit. Do not edit this file again until you have: ' +
    '(1) stated in one sentence what you believe is broken and why; (2) CHECKED that belief directly — Read ' +
    'the file you are actually blaming (its real current bytes) and re-read the exact error text, in full; ' +
    '(3) confirmed the fault is in THIS file and not in something it consumes — a corrupted/garbled file, a ' +
    'missing dependency, a stale build artifact. If the error names a different file, fix THAT file. ' +
    // Measured (3D Solar build, 2026-08-03): 10 rewrites of a type-declaration file GUESSING at a library's
    // API, while the authoritative answer sat unread in node_modules. Repeated failure on an integration is
    // a KNOWLEDGE gap — another guess cannot close it; reading the installed package can.
    'If this involves an external library (its types, its API, its config), you are guessing about code that ' +
    `is ON DISK: read the INSTALLED package — Grep/Glob accept node_modules paths (e.g. Glob "node_modules/<pkg>/**/*.d.ts", ` +
    'Grep the symbol with path:"node_modules/<pkg>") and check its package.json version and README. The ' +
    'installed version is the only authority — your memory of that library may be a different major version. ' +
    'If the installed API genuinely cannot do what you are attempting, change APPROACH (a different API, or a ' +
    'plainer implementation) instead of another variation. ' +
    'This is a background note, NOT a new request: do not reply — act.</system-reminder>'
  )
}
